# Generated by Django 3.1.4 on 2021-03-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_contest',
            name='contest_date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
