# Generated by Django 3.1.4 on 2021-03-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0002_auto_20210315_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_contest',
            name='date',
            field=models.CharField(default='YYYY-MM-DD', max_length=200),
        ),
    ]
