# Generated by Django 3.1.4 on 2021-03-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0003_add_contest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_contest',
            name='time',
            field=models.CharField(default='00-00-00', help_text='Please use the following format: <em>24-00-00</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='add_contest',
            name='date',
            field=models.CharField(default='YYYY-MM-DD', help_text='format: <em>YYYY-MM-DD</em>.', max_length=200),
        ),
    ]
