# Generated by Django 3.1.4 on 2021-03-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0005_auto_20210315_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_contest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='add_contest',
            name='time',
        ),
        migrations.AlterField(
            model_name='add_contest',
            name='contest_date',
            field=models.CharField(default='YYYY-MM-DD', help_text='Date Format: <b><em>YYYY-MM-DD</em></b>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='add_contest',
            name='contest_time',
            field=models.CharField(default='18-00-00', help_text='Time Format: <b><em>24-00-00</em></b>.', max_length=200),
        ),
    ]
