# Generated by Django 3.1.4 on 2021-03-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0006_auto_20210315_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_contest',
            name='contest_time',
            field=models.CharField(default='18:00:00', help_text='Time Format: <b><em>24:00:00</em></b>.', max_length=200),
        ),
    ]
